'use client'
import { useState } from 'react'
import { useRouter, usePathname } from 'next/navigation'
import SharedHeader from '@/components/SharedHeader'
import SharedFooter from '@/components/SharedFooter'

const SUB_NAV = [
  { label: 'AEO Guide',          href: '/resources/aeo-guide' },
  { label: 'llms.txt Generator', href: '/resources/llms-txt' },
  { label: 'BLUF Templates',     href: '/resources/bluf-templates' },
  { label: 'Blog',               href: '/resources/blog' },
  { label: 'Changelog',          href: '/resources/changelog' },
  { label: 'About',              href: '/resources/about' },
  { label: 'Privacy',            href: '/resources/privacy' },
  { label: 'Terms',              href: '/resources/terms' },
  { label: 'Contact',            href: '/resources/contact' },
]

export default function LLMSTxtPage() {
  const router = useRouter()
  const path = usePathname()
  const [llmsForm, setLlmsForm] = useState({ name:'', domain:'', desc:'', email:'', lang:'en', gpt:true, gem:true, plex:true, claude:true, cop:true, allow:'', disallow:'' })
  const [llmsOutput, setLlmsOutput] = useState('')
  const [llmsRaw, setLlmsRaw] = useState('')
  const [copied, setCopied] = useState('')

  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text)
    setCopied(key); setTimeout(()=>setCopied(''),2000)
  }

  function generateLLMS() {
    const { name, domain, desc, email, lang, gpt, gem, plex, claude, cop, allow, disallow } = llmsForm
    const d = domain || 'yourdomain.com'
    const bots = [
      gpt   && {a:'GPTBot',         n:'OpenAI / ChatGPT'},
      gem   && {a:'Google-Extended',n:'Google / Gemini'},
      plex  && {a:'PerplexityBot',  n:'Perplexity'},
      claude&& {a:'ClaudeBot',      n:'Anthropic / Claude'},
      cop   && {a:'bingbot',        n:'Microsoft / Copilot'},
    ].filter(Boolean) as {a:string;n:string}[]
    const blocked = [!gpt&&'GPTBot',!gem&&'Google-Extended',!plex&&'PerplexityBot',!claude&&'ClaudeBot',!cop&&'bingbot'].filter(Boolean) as string[]
    const allows = allow.split('\n').map(l=>l.trim()).filter(Boolean)
    const disallows = disallow.split('\n').map(l=>l.trim()).filter(Boolean)
    let out = `# llms.txt — generated by Notion Cue\n# Place at: https://${d}/llms.txt\n# Generated: ${new Date().toISOString().split('T')[0]}\n\n# ── Site Information ──\nName: ${name||'Your Site'}\n`
    if(desc) out+=`Description: ${desc}\n`
    out+=`Domain: https://${d}\n`
    if(email) out+=`Contact: ${email}\n`
    out+=`Language: ${lang}\n`
    if(bots.length) {
      out+=`\n# ── AI Bot Permissions ──`
      bots.forEach(b => {
        out+=`\n\n# ${b.n}\nUser-agent: ${b.a}\n`
        if(allows.length) allows.forEach(p=>out+=`Allow: ${p}\n`)
        else out+=`Allow: /\n`
        if(disallows.length) disallows.forEach(p=>out+=`Disallow: ${p}\n`)
      })
    }
    if(blocked.length) {
      out+=`\n\n# ── Blocked AI Bots ──`
      blocked.forEach(b=>out+=`\n\nUser-agent: ${b}\nDisallow: /\n`)
    }
    setLlmsRaw(out)
    setLlmsOutput(out.replace(/^(#.*)$/gm,'<span style="color:var(--muted2)">$1</span>').replace(/^(Name|Description|Domain|Contact|Language|User-agent|Allow|Disallow):/gm,'<span style="color:var(--cyan)">$1</span>:').replace(/: (.+)/g,(_,v)=>`: <span style="color:var(--accent)">${v}</span>`))
  }

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@400;500;600;700&family=Epilogue:wght@300;400;500;700&family=JetBrains+Mono:wght@300;400;500&display=swap');
        *,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
        :root{--bg:#04030c;--card:#100e22;--border:rgba(255,255,255,0.07);--border-h:rgba(255,255,255,0.16);--text:#ede9ff;--muted:rgba(255,255,255,0.75);--muted2:rgba(255,255,255,0.4);--accent:#c8f247;--violet:#7b6cff;--cyan:#22d3ee;--green:#4ade80}
        html{scroll-behavior:smooth}
        body{background:var(--bg);color:var(--text);font-family:'Epilogue',sans-serif;font-weight:300;overflow-x:hidden}
        button,input,textarea,select{font-family:inherit;cursor:pointer}
        input:focus,textarea:focus,select:focus,button:focus{outline:none}
        input[type=checkbox]{width:14px;height:14px;accent-color:var(--accent)}
        ::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);border-radius:2px}
      `}</style>

      <div style={{background:'var(--bg)',minHeight:'100vh',color:'var(--text)'}}>
        <SharedHeader />

        {/* Sub-nav */}
        <div style={{position:'sticky',top:'65px',zIndex:700,background:'rgba(4,3,12,.9)',backdropFilter:'blur(16px)',borderBottom:'1px solid var(--border)',padding:'.6rem 3.5rem',display:'flex',gap:0,overflowX:'auto',marginTop:'65px'}}>
          {SUB_NAV.map(n=>(
            <button key={n.href} onClick={()=>router.push(n.href)} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.06em',textTransform:'uppercase',padding:'.55rem 1rem',background:'none',border:'none',borderBottom:path===n.href?'2px solid var(--accent)':'2px solid transparent',color:path===n.href?'var(--accent)':'var(--muted)',whiteSpace:'nowrap',transition:'all .2s'}}>
              {n.label}
            </button>
          ))}
        </div>

        <div style={{maxWidth:'1200px',margin:'0 auto',padding:'0 3.5rem'}}>
          <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
            <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Tools</div>
            <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>llms.txt<br/><span style={{color:'var(--accent)'}}>Generator</span></h1>
            <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Build a properly formatted llms.txt file in seconds. Configure bot permissions, site metadata, and allowed paths — then copy or download your file.</p>
          </div>

          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'2rem',padding:'4rem 0 6rem',alignItems:'start'}}>
            {/* Form */}
            <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',padding:'2rem',display:'flex',flexDirection:'column',gap:'1.25rem'}}>
              <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1rem',marginBottom:'.25rem'}}>Site Information</div>
              {[{id:'name',label:'Site name',placeholder:'Notion Cue'},{id:'domain',label:'Domain',placeholder:'yourdomain.com'},{id:'desc',label:'Description (optional)',placeholder:'AI visibility platform for SEO professionals'},{id:'email',label:'Contact email (optional)',placeholder:'hello@yourdomain.com'}].map(f=>(
                <div key={f.id} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                  <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.label}</label>
                  <input placeholder={f.placeholder} value={(llmsForm as any)[f.id]} onChange={e=>setLlmsForm(p=>({...p,[f.id]:e.target.value}))}
                    style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.82rem',fontFamily:"'JetBrains Mono',monospace"}} />
                </div>
              ))}
              <div style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>Language</label>
                <select value={llmsForm.lang} onChange={e=>setLlmsForm(p=>({...p,lang:e.target.value}))} style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.82rem'}}>
                  {[['en','English'],['es','Spanish'],['fr','French'],['de','German'],['ja','Japanese'],['zh','Chinese']].map(([v,l])=><option key={v} value={v} style={{background:'#100e22'}}>{l}</option>)}
                </select>
              </div>
              <div style={{height:'1px',background:'var(--border)'}} />
              <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1rem'}}>AI Bot Permissions</div>
              {[{key:'gpt',label:'GPTBot (OpenAI / ChatGPT)'},{key:'gem',label:'Google-Extended (Gemini)'},{key:'plex',label:'PerplexityBot (Perplexity)'},{key:'claude',label:'ClaudeBot (Anthropic / Claude)'},{key:'cop',label:'bingbot (Microsoft / Copilot)'}].map(b=>(
                <label key={b.key} style={{display:'flex',alignItems:'center',gap:'.75rem',cursor:'pointer',fontSize:'.85rem',color:'var(--muted)'}}>
                  <input type="checkbox" checked={(llmsForm as any)[b.key]} onChange={e=>setLlmsForm(p=>({...p,[b.key]:e.target.checked}))} />
                  {b.label}
                </label>
              ))}
              <div style={{height:'1px',background:'var(--border)'}} />
              {[{id:'allow',label:'Allowed paths (one per line)',placeholder:'/\n/blog\n/products'},{id:'disallow',label:'Blocked paths (one per line)',placeholder:'/admin\n/private'}].map(f=>(
                <div key={f.id} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                  <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.label}</label>
                  <textarea placeholder={f.placeholder} value={(llmsForm as any)[f.id]} onChange={e=>setLlmsForm(p=>({...p,[f.id]:e.target.value}))} rows={3}
                    style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.75rem',fontFamily:"'JetBrains Mono',monospace",resize:'vertical'}} />
                </div>
              ))}
              <button onClick={generateLLMS} style={{width:'100%',padding:'.85rem',background:'var(--accent)',color:'var(--bg)',border:'none',borderRadius:'100px',fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'.85rem'}}>Generate llms.txt</button>
            </div>

            {/* Output */}
            <div style={{background:'#0a0818',border:'1px solid var(--border)',borderRadius:'14px',overflow:'hidden',position:'sticky',top:'120px'}}>
              <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'.8rem 1.25rem',borderBottom:'1px solid var(--border)',background:'rgba(255,255,255,.02)'}}>
                <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',color:'var(--muted2)',letterSpacing:'.08em'}}>llms.txt — output</span>
                <div style={{display:'flex',gap:'.5rem'}}>
                  <button onClick={()=>copy(llmsRaw,'llms')} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',color:'var(--violet)',background:'none',border:'none',cursor:'pointer',padding:'.2rem .5rem',borderRadius:'3px'}}>{copied==='llms'?'Copied!':'Copy file'}</button>
                  <button onClick={()=>{const b=new Blob([llmsRaw],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='llms.txt';a.click()}} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',color:'var(--accent)',background:'none',border:'none',cursor:'pointer',padding:'.2rem .5rem',borderRadius:'3px'}}>Download</button>
                </div>
              </div>
              <pre style={{padding:'1.25rem',fontFamily:"'JetBrains Mono',monospace",fontSize:'.75rem',lineHeight:1.8,color:'var(--muted)',minHeight:'360px',whiteSpace:'pre-wrap',wordBreak:'break-word'}} dangerouslySetInnerHTML={{__html:llmsOutput||'<span style="color:var(--muted2)">Fill in the form and click Generate to see your llms.txt output here.</span>'}} />
            </div>
          </div>
        </div>

        <SharedFooter />
      </div>
    </>
  )
}