'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import SharedHeader from '@/components/SharedHeader'
import SharedFooter from '@/components/SharedFooter'

type PageId = 'aeo-guide'|'llms-txt'|'bluf-templates'|'blog'|'changelog'|'about'|'privacy'|'terms'|'contact'

export default function ResourcesPage() {
  const [page, setPage] = useState<PageId>('aeo-guide')
  const [llmsForm, setLlmsForm] = useState({ name:'', domain:'', desc:'', email:'', lang:'en', gpt:true, gem:true, plex:true, claude:true, cop:true, allow:'', disallow:'' })
  const [llmsOutput, setLlmsOutput] = useState('')
  const [llmsRaw, setLlmsRaw] = useState('')
  const [copied, setCopied] = useState('')
  const router = useRouter()

  function go(id: PageId) { setPage(id); window.scrollTo({top:0,behavior:'smooth'}) }

  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text)
    setCopied(key); setTimeout(()=>setCopied(''),2000)
  }

  function generateLLMS() {
    const { name, domain, desc, email, lang, gpt, gem, plex, claude, cop, allow, disallow } = llmsForm
    const d = domain || 'yourdomain.com'
    const bots = [
      gpt   && {a:'GPTBot',         n:'OpenAI / ChatGPT'},
      gem   && {a:'Google-Extended',n:'Google / Gemini'},
      plex  && {a:'PerplexityBot',  n:'Perplexity'},
      claude&& {a:'ClaudeBot',      n:'Anthropic / Claude'},
      cop   && {a:'bingbot',        n:'Microsoft / Copilot'},
    ].filter(Boolean) as {a:string;n:string}[]
    const blocked = [!gpt&&'GPTBot',!gem&&'Google-Extended',!plex&&'PerplexityBot',!claude&&'ClaudeBot',!cop&&'bingbot'].filter(Boolean) as string[]
    const allows = allow.split('\n').map(l=>l.trim()).filter(Boolean)
    const disallows = disallow.split('\n').map(l=>l.trim()).filter(Boolean)
    let out = `# llms.txt — generated by Notion Cue\n# Place at: https://${d}/llms.txt\n# Generated: ${new Date().toISOString().split('T')[0]}\n\n# ── Site Information ──\nName: ${name||'Your Site'}\n`
    if(desc) out+=`Description: ${desc}\n`
    out+=`Domain: https://${d}\n`
    if(email) out+=`Contact: ${email}\n`
    out+=`Language: ${lang}\n`
    if(bots.length) {
      out+=`\n# ── AI Bot Permissions ──`
      bots.forEach(b => {
        out+=`\n\n# ${b.n}\nUser-agent: ${b.a}\n`
        if(allows.length) allows.forEach(p=>out+=`Allow: ${p}\n`)
        else out+=`Allow: /\n`
        if(disallows.length) disallows.forEach(p=>out+=`Disallow: ${p}\n`)
      })
    }
    if(blocked.length) {
      out+=`\n\n# ── Blocked AI Bots ──`
      blocked.forEach(b=>out+=`\n\nUser-agent: ${b}\nDisallow: /\n`)
    }
    setLlmsRaw(out)
    setLlmsOutput(out.replace(/^(#.*)$/gm,'<span style="color:var(--muted2)">$1</span>').replace(/^(Name|Description|Domain|Contact|Language|User-agent|Allow|Disallow):/gm,'<span style="color:var(--cyan)">$1</span>:').replace(/: (.+)/g,(_,v)=>`: <span style="color:var(--accent)">${v}</span>`))
  }

  const navLinks: {id:PageId;label:string}[] = [
    {id:'aeo-guide',label:'AEO Guide'},{id:'llms-txt',label:'llms.txt Generator'},{id:'bluf-templates',label:'BLUF Templates'},{id:'blog',label:'Blog'},{id:'changelog',label:'Changelog'},{id:'about',label:'About'},{id:'privacy',label:'Privacy'},{id:'terms',label:'Terms'},{id:'contact',label:'Contact'},
  ]

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@400;500;600;700&family=Epilogue:wght@300;400;500;700&family=JetBrains+Mono:wght@300;400;500&display=swap');
        *,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
        :root{--bg:#04030c;--bg2:#070613;--card:#100e22;--border:rgba(255,255,255,0.07);--border-h:rgba(255,255,255,0.16);--text:#ede9ff;--muted:rgba(255,255,255,0.75);--muted2:rgba(237,233,255,0.22);--accent:#c8f247;--violet:#7b6cff;--cyan:#22d3ee;--rose:#f472b6;--green:#4ade80}
        html{scroll-behavior:smooth}
        body{background:var(--bg);color:var(--text);font-family:'Epilogue',sans-serif;font-weight:300;overflow-x:hidden}
        button,input,textarea,select{font-family:inherit;cursor:pointer}
        input:focus,textarea:focus,select:focus{outline:none}
        a{color:inherit;text-decoration:none}
        .nav-link:hover{color:var(--text)!important}
        .card-h:hover{border-color:var(--border-h)!important;transform:translateY(-3px)}
        .blog-card:hover{border-color:var(--border-h)!important;transform:translateY(-4px)}
        .blog-card:hover .blog-title{color:var(--accent)}
        .tmpl-card:hover{border-color:var(--border-h)!important}
        .toc-link:hover{color:var(--accent)!important}
        .prose h2{font-family:'Familjen Grotesk',sans-serif;font-weight:700;font-size:1.5rem;letter-spacing:-.02em;margin:2.5rem 0 .75rem}
        .prose h3{font-family:'Familjen Grotesk',sans-serif;font-weight:600;font-size:1.1rem;margin:2rem 0 .5rem}
        .prose p{font-size:.93rem;color:var(--muted);line-height:1.85;margin-bottom:1rem}
        .prose ul,.prose ol{padding-left:1.5rem;margin-bottom:1rem}
        .prose li{font-size:.9rem;color:var(--muted);line-height:1.75;margin-bottom:.35rem}
        .prose a{color:var(--accent)}
        .prose strong{color:var(--text);font-weight:500}
        .callout{background:rgba(123,108,255,.06);border:1px solid rgba(123,108,255,.2);border-radius:10px;padding:1.1rem 1.4rem;margin:1.5rem 0}
        .callout p{margin:0!important;color:var(--text)!important;font-size:.88rem!important}
        ::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.1);border-radius:2px}
        @keyframes fadeIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}
        .fade{animation:fadeIn .35s ease both}
        input[type=checkbox]{width:14px;height:14px;accent-color:var(--accent)}
      `}</style>

      <div style={{background:'var(--bg)',minHeight:'100vh',color:'var(--text)',fontFamily:"'Epilogue',sans-serif"}}>

        {/* NAV */}
       <SharedHeader />

        {/* SUB-NAV */}
        <div style={{position:'sticky',top:'65px',zIndex:700,background:'rgba(4,3,12,.9)',backdropFilter:'blur(16px)',borderBottom:'1px solid var(--border)',padding:'.6rem 3.5rem',display:'flex',gap:0,overflowX:'auto'}}>
          {navLinks.map(n=>(
            <button key={n.id} onClick={()=>go(n.id)} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.06em',textTransform:'uppercase',padding:'.55rem 1rem',background:'none',border:'none',borderBottom:page===n.id?'2px solid var(--accent)':'2px solid transparent',color:page===n.id?'var(--accent)':'var(--muted)',whiteSpace:'nowrap',transition:'all .2s'}}>
              {n.label}
            </button>
          ))}
        </div>

        <div style={{maxWidth:'1200px',margin:'0 auto',padding:'0 3.5rem'}}>

          {/* ── AEO GUIDE ── */}
          {page==='aeo-guide' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Resources</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>The Complete<br/><span style={{color:'var(--accent)'}}>AEO Guide</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Everything you need to understand Answer Engine Optimisation and get your content cited by ChatGPT, Gemini, Perplexity, and every major LLM.</p>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'220px 1fr',gap:'4rem',padding:'4rem 0 6rem',alignItems:'start'}}>
                <div style={{position:'sticky',top:'120px'}}>
                  <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'12px',padding:'1.4rem'}}>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.62rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--muted2)',marginBottom:'.85rem'}}>Contents</div>
                    {[['#g1','What is AEO?'],['#g2','How LLMs select sources'],['#g3','The AEO scoring model'],['#g4','BLUF content structure'],['#g5','Schema markup for AI'],['#g6','llms.txt setup'],['#g7','E-E-A-T for LLMs'],['#g8','Competitor analysis']].map(([h,l])=>(
                      <a key={h} href={h} className="toc-link" style={{display:'block',fontSize:'.82rem',color:'var(--muted)',padding:'.3rem 0',borderBottom:'1px solid rgba(255,255,255,.04)',transition:'color .2s'}}>{l}</a>
                    ))}
                  </div>
                </div>
                <div className="prose">
                  <h2 id="g1">What is AEO?</h2>
                  <p>Answer Engine Optimisation (AEO) is the practice of structuring your website content so that large language models choose to cite, quote, or recommend your brand when users ask relevant questions. Where traditional SEO targets search engine ranking algorithms, AEO targets the retrieval and citation patterns of AI systems.</p>
                  <p>As of 2026, tools like ChatGPT, Perplexity, Gemini, and Grok collectively field over 2 billion queries per day. A growing share of these queries have commercial or research intent — exactly the queries that historically drove organic search traffic. <strong>Brands that are not visible in AI-generated answers are increasingly invisible to modern buyers.</strong></p>
                  <div className="callout"><p>AEO is not a replacement for SEO. It is the next layer. The technical foundations (fast pages, clean markup, authoritative content) remain essential. AEO adds the citation-specific signals on top.</p></div>
                  <h2 id="g2">How LLMs select sources</h2>
                  <p>Language models do not crawl the web in real time for most queries. Instead, they draw on training data and, for systems with retrieval capabilities (Perplexity, GPT-4o with browse, Gemini), real-time indexed content. In both cases, certain signals make content more likely to be retrieved and cited.</p>
                  <ul>
                    <li><strong>BLUF structure</strong> — content that answers the query in the first two sentences scores higher in retrieval.</li>
                    <li><strong>Structured data</strong> — FAQ, HowTo, and Article schema help models understand content type and extract answers cleanly.</li>
                    <li><strong>Authority signals</strong> — backlinks from trusted domains, author credentials, and citation frequency across the web.</li>
                    <li><strong>Crawlability</strong> — pages blocked by robots.txt or missing from sitemaps cannot be indexed by AI crawlers.</li>
                    <li><strong>llms.txt</strong> — explicitly allowing AI bots signals that your content is available for training and retrieval.</li>
                  </ul>
                  <h2 id="g3">The AEO scoring model</h2>
                  <p>Notion Cue's composite score (0–100) is built from four weighted categories. Content structure accounts for 35% of the score and covers BLUF compliance, heading hierarchy, FAQ blocks, and answer density. Technical AEO covers 30% and includes schema markup completeness, llms.txt status, robots.txt bot allowances, and page speed. Authority signals account for 20% and cover domain authority, citation frequency across LLMs, and E-E-A-T signals. Crawlability makes up the remaining 15% and covers sitemap coverage, crawl budget, and bot-specific access.</p>
                  <h2 id="g4">BLUF content structure</h2>
                  <p>BLUF (Bottom Line Up Front) is a writing convention from military communications adapted for AI-optimised content. The rule is simple: state the most important information in the first sentence, then add supporting detail. LLMs weight the first 50–80 words of a passage 4–8x more heavily when deciding whether to cite it.</p>
                  <p>For a product page, this means the first sentence should state what the product is, who it is for, and its key value proposition — not a brand story or emotive opener.</p>
                  <h2 id="g5">Schema markup for AI</h2>
                  <p>FAQPage schema is the single highest-impact schema type for AI citations. Pages with FAQPage JSON-LD appear in AI Overview citations at 3.2x the rate of equivalent pages without it. HowTo schema is second, particularly for instructional content. Article and BlogPosting schema help models classify content type and extract author credentials.</p>
                  <h2 id="g6">llms.txt setup</h2>
                  <p>Place a plain text file at <code style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.82em',background:'rgba(255,255,255,.06)',padding:'.15em .4em',borderRadius:'4px'}}>yourdomain.com/llms.txt</code> with bot permission declarations. Use the generator in the llms.txt tab to create your file. At minimum, allow GPTBot, PerplexityBot, and Google-Extended unless you have a specific reason to block them.</p>
                  <h2 id="g7">E-E-A-T for LLMs</h2>
                  <p>Google's E-E-A-T framework (Experience, Expertise, Authoritativeness, Trustworthiness) has been adopted informally by multiple LLM evaluation pipelines. Pages with clear author bylines, linked professional credentials, original research, and verifiable citations score higher on authority signals that LLMs use to decide whether to cite a source.</p>
                  <h2 id="g8">Competitor analysis</h2>
                  <p>The fastest way to improve your AEO score is to identify which queries your competitors get cited for that you do not. Notion Cue's content gap analysis runs the same prompt set against your domain and competitor domains and returns a sorted list of citation opportunities ranked by search volume and commercial intent.</p>
                </div>
              </div>
            </div>
          )}

          {/* ── LLMS.TXT GENERATOR ── */}
          {page==='llms-txt' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Tools</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>llms.txt<br/><span style={{color:'var(--accent)'}}>Generator</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Build a properly formatted llms.txt file in seconds. Configure bot permissions, site metadata, and allowed paths — then copy or download your file.</p>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'2rem',padding:'4rem 0 6rem',alignItems:'start'}}>
                {/* Form */}
                <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',padding:'2rem',display:'flex',flexDirection:'column',gap:'1.25rem'}}>
                  <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1rem',marginBottom:'.25rem'}}>Site Information</div>
                  {[{id:'name',label:'Site name',placeholder:'Notion Cue'},{id:'domain',label:'Domain',placeholder:'Notion Cue.com'},{id:'desc',label:'Description (optional)',placeholder:'AI visibility platform for SEO professionals'},{id:'email',label:'Contact email (optional)',placeholder:'hello@yourdomain.com'}].map(f=>(
                    <div key={f.id} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                      <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.label}</label>
                      <input placeholder={f.placeholder} value={(llmsForm as any)[f.id]} onChange={e=>setLlmsForm(p=>({...p,[f.id]:e.target.value}))}
                        style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.82rem',fontFamily:"'JetBrains Mono',monospace",transition:'border-color .2s'}} />
                    </div>
                  ))}
                  <div style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                    <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>Language</label>
                    <select value={llmsForm.lang} onChange={e=>setLlmsForm(p=>({...p,lang:e.target.value}))} style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.82rem'}}>
                      {[['en','English'],['es','Spanish'],['fr','French'],['de','German'],['ja','Japanese'],['zh','Chinese']].map(([v,l])=><option key={v} value={v} style={{background:'#100e22'}}>{l}</option>)}
                    </select>
                  </div>
                  <div style={{height:'1px',background:'var(--border)'}} />
                  <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1rem'}}>AI Bot Permissions</div>
                  {[{key:'gpt',label:'GPTBot (OpenAI / ChatGPT)'},{key:'gem',label:'Google-Extended (Gemini)'},{key:'plex',label:'PerplexityBot (Perplexity)'},{key:'claude',label:'ClaudeBot (Anthropic / Claude)'},{key:'cop',label:'bingbot (Microsoft / Copilot)'}].map(b=>(
                    <label key={b.key} style={{display:'flex',alignItems:'center',gap:'.75rem',cursor:'pointer',fontSize:'.85rem',color:'var(--muted)'}}>
                      <input type="checkbox" checked={(llmsForm as any)[b.key]} onChange={e=>setLlmsForm(p=>({...p,[b.key]:e.target.checked}))} />
                      {b.label}
                    </label>
                  ))}
                  <div style={{height:'1px',background:'var(--border)'}} />
                  {[{id:'allow',label:'Allowed paths (one per line)',placeholder:'/\n/blog\n/products'},{id:'disallow',label:'Blocked paths (one per line)',placeholder:'/admin\n/private'}].map(f=>(
                    <div key={f.id} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                      <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.label}</label>
                      <textarea placeholder={f.placeholder} value={(llmsForm as any)[f.id]} onChange={e=>setLlmsForm(p=>({...p,[f.id]:e.target.value}))} rows={3}
                        style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.75rem',fontFamily:"'JetBrains Mono',monospace",resize:'vertical'}} />
                    </div>
                  ))}
                  <button onClick={generateLLMS} style={{width:'100%',padding:'.85rem',background:'var(--accent)',color:'var(--bg)',border:'none',borderRadius:'100px',fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'.85rem'}}>Generate llms.txt</button>
                </div>

                {/* Output */}
                <div style={{background:'#0a0818',border:'1px solid var(--border)',borderRadius:'14px',overflow:'hidden',position:'sticky',top:'120px'}}>
                  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'.8rem 1.25rem',borderBottom:'1px solid var(--border)',background:'rgba(255,255,255,.02)'}}>
                    <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',color:'var(--muted2)',letterSpacing:'.08em'}}>llms.txt — output</span>
                    <div style={{display:'flex',gap:'.5rem'}}>
                      <button onClick={()=>copy(llmsRaw,'llms')} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',color:'var(--violet)',background:'none',border:'none',cursor:'pointer',padding:'.2rem .5rem',borderRadius:'3px'}}>{copied==='llms'?'Copied!':'Copy file'}</button>
                      <button onClick={()=>{const b=new Blob([llmsRaw],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='llms.txt';a.click()}} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',color:'var(--accent)',background:'none',border:'none',cursor:'pointer',padding:'.2rem .5rem',borderRadius:'3px'}}>Download</button>
                    </div>
                  </div>
                  <pre style={{padding:'1.25rem',fontFamily:"'JetBrains Mono',monospace",fontSize:'.75rem',lineHeight:1.8,color:'var(--muted)',minHeight:'360px',whiteSpace:'pre-wrap',wordBreak:'break-word'}} dangerouslySetInnerHTML={{__html:llmsOutput||'<span style="color:var(--muted2)">Fill in the form and click Generate to see your llms.txt output here.</span>'}} />
                </div>
              </div>
            </div>
          )}

          {/* ── BLUF TEMPLATES ── */}
          {page==='bluf-templates' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Tools</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>BLUF Content<br/><span style={{color:'var(--accent)'}}>Templates</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Ready-to-use templates for AI-optimised content structure. Each template puts the answer first — the pattern LLMs use to decide what to cite.</p>
              </div>
              <div style={{padding:'4rem 0 6rem'}}>
                <div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'1.25rem',marginBottom:'3rem'}}>
                  {[
                    {name:'Homepage / About',tag:'General',sentence:'[Brand] is a [category] [business type] that [core value proposition] for [target audience], [key differentiator].',body:'Founded in [year], [Brand] [brief origin story / expertise note]. [Supporting detail about product range / geography / scale].',use:'Use on: homepage hero, About page intro, Google Business description, llms.txt description field.'},
                    {name:'Product / Category Page',tag:'E-commerce',sentence:'[Brand] sells [product type] in [size/variant range], priced from [price range], with [shipping/delivery offer].',body:'Our [collection name] includes [number] styles across [subcategories]. [Key material/quality note]. [Return policy or trust signal].',use:'Use on: collection pages, category descriptions, product meta descriptions, shopping feed titles.'},
                    {name:'Blog / Guide Post',tag:'Content',sentence:'[Topic] is [definition/direct answer in one sentence].',body:'This guide covers [main points 1, 2, 3] and is intended for [audience]. [Why this matters / context sentence]. [Author credential or source note].',use:'Use on: blog post introductions, FAQ answers, knowledge base articles, how-to guides.'},
                    {name:'Service / SaaS Page',tag:'B2B / SaaS',sentence:'[Product] is a [category] tool that helps [audience] [achieve outcome] by [mechanism], starting at [price/free tier].',body:'[Differentiating feature 1]. [Key integration or compatibility note]. [Social proof — customer count, rating, or notable client].',use:'Use on: feature pages, pricing sections, landing page hero, app store descriptions.'},
                    {name:'FAQ Answer',tag:'Schema-ready',sentence:'Q: [Direct question]\nA: [Answer in one sentence, 15-25 words max].',body:'[1-2 supporting sentences with detail]. [Link to related resource or product if relevant]. [Date or version note if time-sensitive].',use:'Use on: FAQ pages with FAQPage schema, support articles, product description accordions.'},
                    {name:'Comparison / Versus',tag:'Decision content',sentence:'[Option A] is better for [use case A], while [Option B] is better for [use case B].',body:'[Option A] [key advantage] but [key limitation]. [Option B] [key advantage] but [key limitation]. [Recommendation sentence for typical buyer].',use:'Use on: comparison blog posts, versus landing pages, review content, buying guides.'},
                  ].map((t,i)=>(
                    <div key={i} className="tmpl-card" style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',overflow:'hidden',transition:'border-color .25s'}}>
                      <div style={{padding:'1.25rem 1.5rem',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'rgba(255,255,255,.02)'}}>
                        <span style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'.95rem'}}>{t.name}</span>
                        <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',letterSpacing:'.06em',color:'var(--muted2)',border:'1px solid var(--border)',padding:'.2rem .5rem',borderRadius:'4px',background:'rgba(255,255,255,.02)'}}>{t.tag}</span>
                      </div>
                      <div style={{padding:'1.5rem'}}>
                        <div style={{background:'#0a0818',borderRadius:'8px',padding:'1rem',fontSize:'.78rem',lineHeight:1.7,color:'var(--muted)',marginBottom:'1rem',border:'1px solid var(--border)'}}>
                          <span style={{color:'var(--green)',display:'block',padding:'.5rem .75rem',background:'rgba(74,222,128,.05)',borderLeft:'2px solid var(--green)',borderRadius:'0 6px 6px 0',marginBottom:'.5rem',whiteSpace:'pre-wrap'}}>{t.sentence}</span>
                          {t.body}
                        </div>
                        <div style={{fontSize:'.78rem',color:'var(--muted)',lineHeight:1.6,marginBottom:'.85rem'}}>{t.use}</div>
                        <button onClick={()=>copy(t.sentence+'\n'+t.body,'tmpl'+i)} style={{fontFamily:"'Familjen Grotesk',sans-serif",fontSize:'.75rem',fontWeight:600,padding:'.5rem 1rem',border:'1px solid var(--border)',borderRadius:'100px',background:'transparent',color:'var(--muted)',cursor:'pointer',transition:'all .2s'}}>
                          {copied==='tmpl'+i?'Copied!':'Copy template'}
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
                <div style={{height:'1px',background:'var(--border)',marginBottom:'2.5rem'}} />
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.65rem'}}>Why BLUF works for AI</div>
                <div className="prose" style={{maxWidth:'680px'}}>
                  <p>Large language models parse content to find the most directly useful answer to a user query. Studies show that LLMs weight the first 50–80 words of a passage 4–8x more heavily than the rest of the document when deciding whether to cite it. BLUF structure aligns your content with this retrieval pattern — putting the answer exactly where the model looks first.</p>
                  <p>The templates above follow three rules. The answer comes first. The answer is specific (numbers, names, ranges — not vague generalisations). Supporting detail comes after in a separate sentence or paragraph so the model can extract cleanly.</p>
                </div>
              </div>
            </div>
          )}

          {/* ── BLOG ── */}
          {page==='blog' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Resources — Blog</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>AEO &amp; AI Search<br/><span style={{color:'var(--muted)'}}>Insights</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Deep dives on Answer Engine Optimisation, LLM citation strategies, and the future of AI-driven discovery.</p>
              </div>
              <div style={{padding:'4rem 0 6rem'}}>
                <div style={{display:'flex',gap:'.5rem',marginBottom:'2rem',flexWrap:'wrap'}}>
                  {['All','AEO Strategy','Technical','Case Studies','LLM Updates'].map((f,i)=>(
                    <button key={f} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.7rem',padding:'.4rem .9rem',borderRadius:'6px',border:'1px solid var(--border)',background:i===0?'var(--accent)':'transparent',color:i===0?'var(--bg)':'var(--muted)',cursor:'pointer',transition:'all .2s'}}>{f}</button>
                  ))}
                </div>
                <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'1.25rem'}}>
                  {[
                    {emoji:'🧠',bg:'rgba(200,242,71,.06)',tag:'AEO Strategy',date:'Jun 8, 2026',title:"Why 94% of AI-cited pages have structured data — and how to join them",excerpt:"We analysed 50,000 pages cited by ChatGPT, Gemini, and Perplexity. Here's what schema types appear most frequently.",read:'8 min read'},
                    {emoji:'📊',bg:'rgba(123,108,255,.06)',tag:'Case Studies',date:'May 29, 2026',title:'How The Dress Outlet grew AI-referred sessions by 340% in 90 days',excerpt:'A step-by-step breakdown of the llms.txt fix, BLUF rewrites, and schema additions that took ChatGPT citations from near-zero to 33K monthly sessions.',read:'12 min read'},
                    {emoji:'🔬',bg:'rgba(34,211,238,.06)',tag:'Technical',date:'May 14, 2026',title:'llms.txt: the complete technical guide to AI crawler permissions in 2026',excerpt:'Which bots respect it, which ignore it, what format actually works, and why getting this wrong can silently exclude you from AI training pipelines.',read:'10 min read'},
                    {emoji:'🎯',bg:'rgba(244,114,182,.06)',tag:'LLM Updates',date:'Apr 30, 2026',title:"GPT-4o's new citation behaviour: what changed and what it means for your AEO score",excerpt:"OpenAI's April 2026 update changed how GPT-4o selects sources for commercial intent queries. Here's exactly what shifted.",read:'6 min read'},
                    {emoji:'🌐',bg:'rgba(74,222,128,.06)',tag:'AEO Strategy',date:'Apr 12, 2026',title:'International AEO: how to optimise for AI citations across 35 global domains',excerpt:'Managing multi-language, multi-region AEO is a different challenge from single-domain work. Our guide to hreflang, regional llms.txt, and language-specific BLUF.',read:'9 min read'},
                    {emoji:'⚡',bg:'rgba(251,191,36,.06)',tag:'Technical',date:'Mar 28, 2026',title:'Core Web Vitals and AI citations: the surprising connection between page speed and LLM visibility',excerpt:'Perplexity and real-time AI crawlers actively penalise slow pages. Our data shows domains with Good CWV scores get cited 2.1x more often.',read:'7 min read'},
                  ].map((p,i)=>(
                    <div key={i} className="blog-card" style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',overflow:'hidden',transition:'all .25s',cursor:'pointer'}}>
                      <div style={{height:'140px',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'2.2rem',borderBottom:'1px solid var(--border)',background:p.bg}}>{p.emoji}</div>
                      <div style={{padding:'1.4rem'}}>
                        <div style={{display:'flex',alignItems:'center',gap:'.65rem',marginBottom:'.65rem',flexWrap:'wrap'}}>
                          <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--violet)',background:'rgba(123,108,255,.08)',border:'1px solid rgba(123,108,255,.18)',padding:'.2rem .55rem',borderRadius:'4px'}}>{p.tag}</span>
                          <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.62rem',color:'var(--muted2)'}}>{p.date}</span>
                        </div>
                        <div className="blog-title" style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'.95rem',lineHeight:1.25,marginBottom:'.5rem',transition:'color .2s'}}>{p.title}</div>
                        <div style={{fontSize:'.78rem',color:'var(--muted)',lineHeight:1.6,marginBottom:'.85rem'}}>{p.excerpt}</div>
                        <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.62rem',color:'var(--accent)',letterSpacing:'.06em'}}>{p.read} →</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* ── CHANGELOG ── */}
          {page==='changelog' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Company</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>Changelog</h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Every update, improvement, and new feature — documented as it ships.</p>
              </div>
              <div style={{padding:'4rem 0 6rem'}}>
                {[
                  {date:'Jun 2026',v:'v1.4.0',vc:'rgba(200,242,71,.08)',vbc:'rgba(200,242,71,.25)',vtc:'var(--accent)',latest:true,title:'Grok integration + AI Acquisition Report',changes:['Added Grok (xAI) citation tracking to all dashboard plans.','New AI Acquisition Report panel showing session-level data from AI-referred traffic.','BLUF Optimizer now generates 3 rewrite variations per page type.','Improved scan speed by 40% through parallel LLM probing.','Weekly email digest now includes competitor movement alerts.']},
                  {date:'May 2026',v:'v1.3.0',vc:'rgba(123,108,255,.08)',vbc:'rgba(123,108,255,.25)',vtc:'var(--violet)',title:'E-E-A-T Radar + Schema Validator',changes:['E-E-A-T score breakdown with radar chart and per-pillar scores.','Schema markup validator checking 12 schema types for completeness.','Content gap table now shows query intent classification.','Agency plan: white-label PDF report export with custom branding.','llms.txt generator added to Resources section.']},
                  {date:'Apr 2026',v:'v1.2.0',vc:'rgba(34,211,238,.08)',vbc:'rgba(34,211,238,.25)',vtc:'var(--cyan)',title:'Competitor benchmarking launch',changes:['Add up to 10 competitor domains and compare AEO scores side-by-side.','Citation gap analysis: queries where competitors appear but you don\'t.','30-day citation trend chart now visible on dashboard overview.','Claude AI integration for natural-language report summaries.']},
                  {date:'Mar 2026',v:'v1.1.0',vc:'rgba(255,255,255,.03)',vbc:'var(--border)',vtc:'var(--muted2)',title:'Perplexity + Copilot tracking added',changes:['Expanded LLM coverage from 3 to 5 engines (added Perplexity and Bing Copilot).','Sentiment analysis now available on all plans.','Technical audit section: llms.txt validation and robots.txt AI-bot check.','Pro plan: CSV export for all citation and gap data.']},
                  {date:'Feb 2026',v:'v1.0.0',vc:'rgba(255,255,255,.03)',vbc:'var(--border)',vtc:'var(--muted2)',title:'Notion Cue public launch',changes:['Initial launch with ChatGPT, Gemini, and Claude citation tracking.','AEO score (0–100) composite metric across all tracked engines.','Free tier: 1 domain scan per day, 3 LLMs, 7-day history.','Pro tier: 10 domains, 5 LLMs, weekly digest, 90-day history.']},
                ].map((item,i)=>(
                  <div key={i} style={{display:'grid',gridTemplateColumns:'140px 1fr',gap:'2rem',padding:'2rem 0',borderBottom:'1px solid var(--border)',borderTop:i===0?'1px solid var(--border)':'none'}}>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.7rem',color:'var(--muted2)',paddingTop:'.2rem'}}>{item.date}</div>
                    <div>
                      <div style={{display:'flex',alignItems:'center',gap:'.75rem',marginBottom:'.4rem'}}>
                        <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',letterSpacing:'.08em',textTransform:'uppercase',padding:'.2rem .55rem',borderRadius:'4px',border:'1px solid',borderColor:item.vbc,background:item.vc,color:item.vtc}}>{item.v}</span>
                        {item.latest&&<span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.6rem',color:'var(--accent)'}}>Latest</span>}
                      </div>
                      <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1rem',marginBottom:'.65rem'}}>{item.title}</div>
                      <div style={{display:'flex',flexDirection:'column',gap:'.35rem'}}>
                        {item.changes.map((c,ci)=>(
                          <div key={ci} style={{display:'flex',alignItems:'flex-start',gap:'.5rem',fontSize:'.82rem',color:'var(--muted)'}}>
                            <span style={{color:'var(--muted2)',flexShrink:0,marginTop:'.05rem'}}>–</span>{c}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ── ABOUT ── */}
          {page==='about' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Company</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>We built the tool<br/><span style={{color:'var(--accent)'}}>we needed.</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Notion Cue started as an internal tool for a small SEO team trying to understand why some clients showed up in AI answers and others didn't.</p>
              </div>
              <div style={{padding:'4rem 0 6rem',display:'flex',flexDirection:'column',gap:'4rem'}}>
                <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',border:'1px solid var(--border)',borderRadius:'14px',overflow:'hidden'}}>
                  {[{val:'3,400',suf:'+',lbl:'SEO professionals'},{val:'2.1',suf:'M',lbl:'Scans run to date'},{val:'6',suf:'',lbl:'LLMs tracked'},{val:'Feb',suf:' 2026',lbl:'Founded'}].map((s,i)=>(
                    <div key={i} style={{padding:'2rem 1.75rem',borderRight:i<3?'1px solid var(--border)':'none',textAlign:'center'}}>
                      <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'2.4rem',lineHeight:1,color:'#fff',letterSpacing:'-.02em',marginBottom:'.35rem'}}>{s.val}<span style={{color:'var(--accent)',fontSize:'.6em'}}>{s.suf}</span></div>
                      <div style={{fontSize:'.78rem',color:'var(--muted)',lineHeight:1.5}}>{s.lbl}</div>
                    </div>
                  ))}
                </div>
                <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'3rem'}}>
                  <div>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.65rem'}}>Our values</div>
                    {[{title:'Transparency',desc:"We show our methodology. Our scoring model is documented publicly. We don't make claims we can't back up with data."},{title:'Practitioner-first',desc:'Built by SEO practitioners for SEO practitioners. Every feature exists because a real SEO professional needed it to do their job better.'},{title:'Privacy by design',desc:"We don't sell data. We don't run ads. Our business model is subscription revenue, which means our incentives are aligned with yours."}].map((v,i)=>(
                      <div key={i} style={{padding:'1.25rem 0',borderBottom:i<2?'1px solid var(--border)':'none'}}>
                        <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'1.1rem',marginBottom:'.35rem'}}>{v.title}</div>
                        <div style={{fontSize:'.9rem',color:'var(--muted)',lineHeight:1.7}}>{v.desc}</div>
                      </div>
                    ))}
                  </div>
                  <div>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.65rem'}}>Backed by</div>
                    <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'12px',padding:'1.75rem'}}>
                      <p style={{fontSize:'.9rem',color:'var(--muted)',lineHeight:1.75,marginBottom:'1rem'}}>Notion Cue is bootstrapped and profitable. We are not venture-backed. This means we build for our users, not for a growth-at-all-costs exit timeline.</p>
                      <div style={{height:'1px',background:'var(--border)',margin:'1rem 0'}} />
                      <p style={{fontSize:'.9rem',color:'var(--muted)',lineHeight:1.75,margin:0}}>Revenue comes from subscriptions. No ads, no data brokering, no affiliate marketing. If the product doesn't help you, you cancel. That's the only accountability mechanism we want.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ── PRIVACY ── */}
          {page==='privacy' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Legal</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>Privacy<br/><span style={{color:'var(--muted)'}}>Policy</span></h1>
                <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.75rem',color:'var(--muted2)'}}>Last updated: 1 June 2026 · Effective: 1 June 2026</p>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'220px 1fr',gap:'4rem',padding:'4rem 0 6rem',alignItems:'start'}}>
                <div style={{position:'sticky',top:'120px'}}>
                  <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'12px',padding:'1.4rem'}}>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.62rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--muted2)',marginBottom:'.85rem'}}>Sections</div>
                    {[['#p1','Information we collect'],['#p2','How we use your data'],['#p3','Data sharing'],['#p4','Data retention'],['#p5','Your rights'],['#p6','Cookies'],['#p7','Security'],['#p8','Contact us']].map(([h,l])=>(
                      <a key={h} href={h} className="toc-link" style={{display:'block',fontSize:'.82rem',color:'var(--muted)',padding:'.3rem 0',borderBottom:'1px solid rgba(255,255,255,.04)',transition:'color .2s'}}>{l}</a>
                    ))}
                  </div>
                </div>
                <div className="prose">
                  <p>Notion Cue ("we", "our", "us") is committed to protecting your personal information. This policy explains what data we collect, why we collect it, and how you can control it.</p>
                  <h2 id="p1">1. Information we collect</h2>
                  <p>We collect the following categories of information when you use Notion Cue.</p>
                  <ul><li><strong>Account data</strong> — email address, name, and password (hashed) when you register.</li><li><strong>Usage data</strong> — domains you scan, features you use, pages you visit, and timestamps of activity.</li><li><strong>Payment data</strong> — processed entirely by Stripe. We store only the last 4 digits, card type, and expiry date.</li><li><strong>Technical data</strong> — IP address, browser type, device type, and operating system collected automatically.</li></ul>
                  <h2 id="p2">2. How we use your data</h2>
                  <p>We use your data only to provide and improve the Notion Cue service.</p>
                  <ul><li>Create and manage your account and subscription.</li><li>Run domain scans and return AEO analysis results to you.</li><li>Send weekly digest emails if you have opted in.</li><li>Debug errors and improve product performance.</li><li>Comply with legal obligations.</li></ul>
                  <div className="callout"><p>We do not sell your data. We do not share it with advertisers. We do not use it for any purpose outside of operating the Notion Cue service.</p></div>
                  <h2 id="p3">3. Data sharing</h2>
                  <p>We share data with the following third-party services strictly for operating the product.</p>
                  <ul><li><strong>Stripe</strong> — payment processing.</li><li><strong>Supabase</strong> — database hosting (EU servers, GDPR-compliant).</li><li><strong>Vercel</strong> — hosting and edge functions.</li><li><strong>OpenAI</strong> — AI analysis (domain names and scan requests are sent to the API).</li></ul>
                  <h2 id="p4">4. Data retention</h2>
                  <p>We retain your account data for as long as your account is active. Scan history is retained for 7 days (Free), 90 days (Pro), or 365 days (Agency). When you delete your account, all personal data is permanently deleted within 30 days.</p>
                  <h2 id="p5">5. Your rights</h2>
                  <p>Under GDPR and equivalent regulations, you have the right to access, correct, export, or delete your data at any time. Email <a href="mailto:privacy@Notion Cue.com" style={{color:'var(--accent)'}}>privacy@Notion Cue.com</a>.</p>
                  <h2 id="p6">6. Cookies</h2>
                  <p>We use only essential cookies required for authentication and session management. We do not use advertising cookies or third-party tracking cookies.</p>
                  <h2 id="p7">7. Security</h2>
                  <p>All data is transmitted over HTTPS. Passwords are hashed using bcrypt. Database access is restricted to Notion Cue infrastructure only. We conduct regular security reviews.</p>
                  <h2 id="p8">8. Contact us</h2>
                  <p>For privacy-related questions, contact us at <a href="mailto:privacy@Notion Cue.com" style={{color:'var(--accent)'}}>privacy@Notion Cue.com</a>.</p>
                </div>
              </div>
            </div>
          )}

          {/* ── TERMS ── */}
          {page==='terms' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Legal</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>Terms of<br/><span style={{color:'var(--muted)'}}>Service</span></h1>
                <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.75rem',color:'var(--muted2)'}}>Last updated: 1 June 2026 · Effective: 1 June 2026</p>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'220px 1fr',gap:'4rem',padding:'4rem 0 6rem',alignItems:'start'}}>
                <div style={{position:'sticky',top:'120px'}}>
                  <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'12px',padding:'1.4rem'}}>
                    <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.62rem',letterSpacing:'.12em',textTransform:'uppercase',color:'var(--muted2)',marginBottom:'.85rem'}}>Sections</div>
                    {[['#t1','Acceptance'],['#t2','Service description'],['#t3','Account terms'],['#t4','Acceptable use'],['#t5','Payment'],['#t6','Cancellation'],['#t7','Disclaimer'],['#t8','Limitation of liability'],['#t9','Governing law']].map(([h,l])=>(
                      <a key={h} href={h} className="toc-link" style={{display:'block',fontSize:'.82rem',color:'var(--muted)',padding:'.3rem 0',borderBottom:'1px solid rgba(255,255,255,.04)',transition:'color .2s'}}>{l}</a>
                    ))}
                  </div>
                </div>
                <div className="prose">
                  <h2 id="t1">1. Acceptance</h2>
                  <p>By accessing or using Notion Cue, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>
                  <h2 id="t2">2. Service description</h2>
                  <p>Notion Cue provides AI visibility analysis, AEO scoring, and related tools. We reserve the right to modify or discontinue any part of the service with reasonable notice.</p>
                  <h2 id="t3">3. Account terms</h2>
                  <p>You must provide accurate information when registering. You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorised access.</p>
                  <h2 id="t4">4. Acceptable use</h2>
                  <p>You may not use Notion Cue to scan domains you do not own or have permission to analyse, to attempt to reverse-engineer our scoring algorithms, to resell or redistribute data without a written agreement, or to violate any applicable laws.</p>
                  <h2 id="t5">5. Payment</h2>
                  <p>Paid plans are billed monthly or annually in advance. All fees are non-refundable except as required by law or as stated in our refund policy. We may change pricing with 30 days' notice.</p>
                  <h2 id="t6">6. Cancellation</h2>
                  <p>You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period. You retain access until then.</p>
                  <h2 id="t7">7. Disclaimer</h2>
                  <p>Notion Cue is provided "as is" without warranties of any kind. We do not guarantee specific outcomes such as citation increases or traffic improvements.</p>
                  <h2 id="t8">8. Limitation of liability</h2>
                  <p>To the maximum extent permitted by law, Notion Cue's liability for any claim is limited to the amount you paid us in the 12 months preceding the claim.</p>
                  <h2 id="t9">9. Governing law</h2>
                  <p>These terms are governed by the laws of England and Wales. Disputes shall be resolved in the courts of England and Wales.</p>
                </div>
              </div>
            </div>
          )}

          {/* ── CONTACT ── */}
          {page==='contact' && (
            <div className="fade">
              <div style={{padding:'6rem 0 4rem',borderBottom:'1px solid var(--border)'}}>
                <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.68rem',letterSpacing:'.18em',textTransform:'uppercase',color:'var(--violet)',marginBottom:'.75rem'}}>Company</div>
                <h1 style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'clamp(2.5rem,6vw,5rem)',lineHeight:.95,letterSpacing:'-.03em',marginBottom:'1.25rem'}}>Get in<br/><span style={{color:'var(--accent)'}}>touch.</span></h1>
                <p style={{fontSize:'1.05rem',color:'var(--muted)',lineHeight:1.75,maxWidth:'520px'}}>Questions about pricing, the product, or a partnership? We read every message.</p>
              </div>
              <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'4rem',padding:'4rem 0 6rem',alignItems:'start'}}>
                <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'14px',padding:'2rem',display:'flex',flexDirection:'column',gap:'1.1rem'}}>
                  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1rem'}}>
                    {[{l:'First name',ph:'Jane'},{l:'Last name',ph:'Smith'}].map(f=>(
                      <div key={f.l} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                        <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.l}</label>
                        <input placeholder={f.ph} style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.85rem'}} />
                      </div>
                    ))}
                  </div>
                  {[{l:'Email',ph:'jane@company.com',t:'email'},{l:'Company website',ph:'yoursite.com',t:'text'}].map(f=>(
                    <div key={f.l} style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                      <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>{f.l}</label>
                      <input type={f.t} placeholder={f.ph} style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.85rem'}} />
                    </div>
                  ))}
                  <div style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                    <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>Subject</label>
                    <select style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.65rem 1rem',color:'var(--text)',fontSize:'.85rem'}}>
                      {['General question','Pricing / sales','Bug report','Partnership','Press / media'].map(o=><option key={o} style={{background:'#100e22'}}>{o}</option>)}
                    </select>
                  </div>
                  <div style={{display:'flex',flexDirection:'column',gap:'.3rem'}}>
                    <label style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.65rem',letterSpacing:'.08em',textTransform:'uppercase',color:'var(--muted2)'}}>Message</label>
                    <textarea rows={5} placeholder="Tell us what you need..." style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border-h)',borderRadius:'8px',padding:'.75rem 1rem',color:'var(--text)',fontSize:'.85rem',resize:'vertical',fontFamily:'inherit'}} />
                  </div>
                  <button style={{width:'100%',padding:'.85rem',background:'var(--accent)',color:'var(--bg)',border:'none',borderRadius:'100px',fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:700,fontSize:'.85rem'}}>Send message</button>
                </div>
                <div style={{display:'flex',flexDirection:'column',gap:'1.25rem'}}>
                  {[{icon:'✉️',title:'Email',val:'hello@Notion Cue.com',sub:'We reply within 24 hours.'},{icon:'💬',title:'Live chat',val:'Available on the dashboard',sub:'Pro and Agency plan users get priority support.'},{icon:'🐦',title:'Twitter / X',val:'@Notion Cue',sub:'For product updates and quick questions.'}].map((c,i)=>(
                    <div key={i} style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:'12px',padding:'1.5rem',display:'flex',gap:'1.1rem',alignItems:'flex-start'}}>
                      <div style={{width:'42px',height:'42px',borderRadius:'10px',background:'rgba(255,255,255,.04)',border:'1px solid var(--border)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'1.1rem',flexShrink:0}}>{c.icon}</div>
                      <div>
                        <div style={{fontFamily:"'Familjen Grotesk',sans-serif",fontWeight:600,fontSize:'.95rem',marginBottom:'.2rem'}}>{c.title}</div>
                        <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.75rem',color:'var(--accent)',marginBottom:'.25rem'}}>{c.val}</div>
                        <div style={{fontSize:'.8rem',color:'var(--muted)',lineHeight:1.5}}>{c.sub}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

        </div>

        {/* FOOTER */}
        <SharedFooter />
        
        <div style={{borderTop:'1px solid var(--border)',padding:'1.4rem 3.5rem',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
          <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.63rem',color:'var(--muted2)',letterSpacing:'.04em'}}>© 2026 <span style={{color:'var(--muted)'}}>Notion Cue</span> — AI Visibility Intelligence Platform</span>
          <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:'.63rem',color:'var(--muted2)',letterSpacing:'.04em'}}>Built for the next era of search.</span>
        </div>

      </div>
    </>
  )
}