export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { name, desc, email, lang, gpt, gem, plex, claude: claudeBot, cop, allow, disallow } = body
    const domain: string = (body.domain || '').replace(/^https?:\/\//, '').trim()

    if (!domain) return Response.json({ error: 'Domain is required' }, { status: 400 })

    const apiKey = process.env.NVIDIA_API_KEY
    if (!apiKey) return Response.json({ error: 'Missing API key' }, { status: 500 })

    const today = new Date().toISOString().split('T')[0]
    const allowPaths: string[] = allow ? allow.split('\n').map((l: string) => l.trim()).filter(Boolean) : ['/']
    const disallowPaths: string[] = disallow ? disallow.split('\n').map((l: string) => l.trim()).filter(Boolean) : []

    const botLines = [
      `User-agent: GPTBot\n${gpt ? 'Allow: /' : 'Disallow: /'}`,
      `User-agent: Google-Extended\n${gem ? 'Allow: /' : 'Disallow: /'}`,
      `User-agent: PerplexityBot\n${plex ? 'Allow: /' : 'Disallow: /'}`,
      `User-agent: ClaudeBot\n${claudeBot ? 'Allow: /' : 'Disallow: /'}`,
      `User-agent: bingbot\n${cop ? 'Allow: /' : 'Disallow: /'}`,
    ].join('\n\n')

    const allowedBotNames = [gpt && 'GPTBot', gem && 'Google-Extended', plex && 'PerplexityBot', claudeBot && 'ClaudeBot', cop && 'bingbot'].filter(Boolean).join(', ')
    const blockedBotNames = [!gpt && 'GPTBot', !gem && 'Google-Extended', !plex && 'PerplexityBot', !claudeBot && 'ClaudeBot', !cop && 'bingbot'].filter(Boolean).join(', ')

    const systemPrompt = 'You are an expert in AI SEO and llms.txt generation. Always respond with valid JSON only — no markdown, no code fences, no preamble.'

    const userPrompt = `Generate an llms.txt file for the domain: ${domain}

User provided:
- Name: ${name || 'infer from domain'}
- Description: ${desc || 'infer from domain'}
- Email: ${email || 'none'}
- Language: ${lang || 'en'}
- Allowed bots: ${allowedBotNames || 'none'}
- Blocked bots: ${blockedBotNames || 'none'}
- Allow paths: ${allowPaths.join(', ')}
- Disallow paths: ${disallowPaths.join(', ') || 'none'}

Research what ${domain} does. Write realistic content, not placeholders.

Respond with ONLY this JSON (no markdown, no extra text):
{
  "company_name": "string",
  "tagline": "one sentence what this site does and for whom",
  "category": "SaaS or eCommerce or Blog or Agency or Tool etc",
  "llms_txt": "string — the full llms.txt file content as a single string with newlines as \\n",
  "llms_full_txt": "string — extended version with detailed feature and page descriptions",
  "validation": [
    {"check": "Site name present", "pass": true, "note": "string"},
    {"check": "BLUF description", "pass": true, "note": "string"},
    {"check": "Key pages listed", "pass": true, "note": "string"},
    {"check": "AI bot rules defined", "pass": true, "note": "string"},
    {"check": "Blocked bots configured", "pass": ${blockedBotNames ? 'true' : 'false'}, "note": "${blockedBotNames || 'none blocked'}"},
    {"check": "Path permissions set", "pass": true, "note": "${allowPaths.length} allow rule(s)"},
    {"check": "Contact info", "pass": ${!!email}, "note": "${email || 'no email provided'}"},
    {"check": "Spec compliant format", "pass": true, "note": "follows llms.txt standard"}
  ],
  "topics": ["topic1", "topic2", "topic3", "topic4", "topic5"],
  "aeo_lift": 12,
  "engines_helped": ${[gpt, gem, plex, claudeBot, cop].filter(Boolean).length}
}

For the llms_txt field, generate content like this (replace placeholders):
# llms.txt — ${domain}
# Generated by Notion Cue | ${today}
# Place at: https://${domain}/llms.txt

Name: [company name]
Description: [one sentence BLUF]
Domain: https://${domain}
${email ? 'Contact: ' + email : ''}
Language: ${lang || 'en'}

# What We Do
# [2-3 sentences about what the site does and for whom]

# Key Pages
${allowPaths.map((p: string) => 'Allow: ' + p).join('\n')}
${disallowPaths.map((p: string) => 'Disallow: ' + p).join('\n')}

# AI Bot Permissions
${botLines}

# Topics
# [topic 1]
# [topic 2]
# [topic 3]`

    const response = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'meta/llama-3.1-8b-instruct',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user',   content: userPrompt },
        ],
        max_tokens: 2000,
        temperature: 0.4,
      }),
    })

    const rawText = await response.text()
    console.log('llms-gen status:', response.status)
    console.log('llms-gen preview:', rawText.slice(0, 300))

    if (!response.ok) {
      console.error('NVIDIA error:', rawText)
      return Response.json({ error: 'API error: ' + response.status }, { status: 500 })
    }

    const json = JSON.parse(rawText)
    const text = json.choices?.[0]?.message?.content

    if (!text) {
      return Response.json({ error: 'Empty response from AI' }, { status: 500 })
    }

    console.log('llms-gen content preview:', text.slice(0, 300))

    // Strip any markdown fences and find the JSON object
    const stripped = text.replace(/```json|```/g, '').trim()
    const jsonMatch = stripped.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      console.error('No JSON found in:', stripped.slice(0, 300))
      return Response.json({ error: 'AI returned invalid format. Try again.' }, { status: 500 })
    }

    let data
    try {
      data = JSON.parse(jsonMatch[0])
    } catch (parseErr) {
      console.error('JSON parse error:', parseErr)
      console.error('Attempted to parse:', jsonMatch[0].slice(0, 300))
      return Response.json({ error: 'AI returned malformed JSON. Try again.' }, { status: 500 })
    }

    return Response.json(data)

  } catch (err) {
    console.error('llms-gen catch:', err)
    return Response.json({ error: String(err) }, { status: 500 })
  }
}